#!/bin/bash

##
## download
##

pkg_name="nodejs-$VER_NODEJS"
[ "$packages_force_compilation" == "N" ] && pkg_result=$(package_download $pkg_name)
if [ "$pkg_result" != "success" ]; then
    url="http://nodejs.org/dist/v$VER_NODEJS/node-v$VER_NODEJS.tar.gz"
    file=node-v$VER_NODEJS.tar.gz
    result=$(file_download --url $url --file $file --cache-dir-name downloads --check-file-size 10000000)
    if [ "$result" == "error" ]; then
        echo "Error: Unable to download $file file!"
        exit 1
    fi
fi

##
## install
##

if [ "$pkg_result" != "success" ]; then
    echo "Compile nodejs:"
    [ -d $INSTALL_DIR/nodejs ] && rm -rf $INSTALL_DIR/nodejs
    tar -zxf node-v$VER_NODEJS.tar.gz
    cd node-v$VER_NODEJS
    ./configure \
        --prefix=$INSTALL_DIR/nodejs \
    && make && make install && echo "nodejs installed successfully!" \
    && rm -rfv $INSTALL_DIR/nodejs/share
    cd ..
    echo "Strip symbols:"
    development_strip_symbols $INSTALL_DIR/nodejs/bin
    development_strip_symbols $INSTALL_DIR/nodejs/lib
    echo "Create package:"
    package_create $INSTALL_DIR/nodejs $pkg_name
else
    echo "Install nodejs from package:"
    package_restore $pkg_name
fi

# check
if [ ! -f $INSTALL_DIR/nodejs/bin/node ]; then
    echo "Error: nodejs has NOT been installed successfully!"
    exit 1
fi

##
## configure
##

echo "Shared library dependencies for $INSTALL_DIR/nodejs/bin/node:"
ldd $INSTALL_DIR/nodejs/bin/node

# set files permission
chown -R root:root $INSTALL_DIR/nodejs

##
## post install
##

[ -f node-v$VER_NODEJS.tar.gz ] && rm node-v$VER_NODEJS.tar.gz
[ -d node-v$VER_NODEJS ] && rm -rf node-v$VER_NODEJS

# save package version
package_add_version "nodejs" "$VER_NODEJS"

# add directories to create hashes
hashes_add_dir $INSTALL_DIR/nodejs/bin
hashes_add_dir $INSTALL_DIR/nodejs/lib

exit 0

