#!/bin/bash

##
## download
##

pkg_name="GeoIP-$GEOIP_VERSION"
[ "$packages_force_compilation" == "N" ] && pkg_result=$(package_download $pkg_name)
if [ "$pkg_result" != "success" ]; then
    url="http://geolite.maxmind.com/download/geoip/api/c/GeoIP-$GEOIP_VERSION.tar.gz"
    file=GeoIP-$GEOIP_VERSION.tar.gz
    result=$(file_download --url $url --file $file --cache-dir-name downloads --check-file-size 500000)
    if [ "$result" == "error" ]; then
        echo "Error: Unable to download $file file!"
        exit 1
    fi
fi

url="http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz"
file=GeoLiteCity.dat.gz
result=$(file_download --url $url --file $file --cache-dir-name downloads --check-file-size 10000000)
if [ "$result" == "error" ]; then
    echo "Error: Unable to download $file file!"
    exit 1
fi

##
## install
##

if [ "$pkg_result" != "success" ]; then
    echo "Compile GeoIP:"
    [ -d $INSTALL_DIR/geoip ] && rm -rf $INSTALL_DIR/geoip
    tar -zxf GeoIP-$GEOIP_VERSION.tar.gz
    cd GeoIP-$GEOIP_VERSION
    libtoolize -f && ./configure \
        --prefix=$INSTALL_DIR/geoip \
    && make && make install \
    && echo "GeoIP installed successfully!" \
    && rm -rf $INSTALL_DIR/geoip/share/man
    cd ..
    echo "Strip symbols:"
    development_strip_symbols $INSTALL_DIR/geoip/bin
    development_strip_symbols $INSTALL_DIR/geoip/lib
    echo "Create package:"
    package_create $INSTALL_DIR/geoip $pkg_name
else
    echo "Install GeoIP from package:"
    package_restore $pkg_name
fi

# check
if [ ! -f $INSTALL_DIR/geoip/bin/geoiplookup ]; then
    echo "Error: GeoIP has NOT been installed successfully!"
    exit 1
fi

echo "Install GeoIP database:"
cp -v GeoLiteCity.dat.gz $INSTALL_DIR/geoip/share/GeoIP/GeoLiteCity.dat.gz
gunzip -d $INSTALL_DIR/geoip/share/GeoIP/GeoLiteCity.dat.gz
mv $INSTALL_DIR/geoip/share/GeoIP/GeoLiteCity.dat $INSTALL_DIR/geoip/share/GeoIP/GeoIPCity.dat

# check
if [ ! -f $INSTALL_DIR/geoip/share/GeoIP/GeoIPCity.dat ]; then
    echo "Error: GeoIP database has NOT been installed successfully!"
    exit 1
else
    echo "GeoIP database installed successfully!"
fi

##
## configure
##

echo "Link libraries:"
development_link_libraries $INSTALL_DIR/geoip/lib

echo "Copy includes:"
rm /usr/include/GeoIP*.h > /dev/null 2>&1
cp -v $INSTALL_DIR/geoip/include/*.h /usr/include/

echo "Shared library dependencies for $INSTALL_DIR/geoip/bin/geoiplookup:"
ldd $INSTALL_DIR/geoip/bin/geoiplookup

# set files permission
chown -R root:root $INSTALL_DIR/geoip
chmod 644 $INSTALL_DIR/geoip/share/GeoIP/GeoIPCity.dat

##
## post install
##

[ -f geoip-${GEOIP_VERSION}${PACKAGE_SUFFIX} ] && rm geoip-${GEOIP_VERSION}${PACKAGE_SUFFIX}
[ -f GeoIP-$GEOIP_VERSION.tar.gz ] && rm GeoIP-$GEOIP_VERSION.tar.gz
[ -f GeoLiteCity.dat.gz ] && rm GeoLiteCity.dat.gz
[ -d GeoIP-$GEOIP_VERSION ] && rm -rf GeoIP-$GEOIP_VERSION

# save package version
package_add_version "geoip" "$GEOIP_VERSION"

# add directories to create hashes
hashes_add_dir $INSTALL_DIR/geoip/bin
hashes_add_dir $INSTALL_DIR/geoip/lib

exit 0
