#!/bin/bash

##
## check dependencies
##

if [ ! -f $INSTALL_DIR/zlib/lib/libz.so ]; then
    echo "Error: OpenSSL requires zlib!"
    exit 1
fi

##
## download
##

pkg_name="openssl-$VER_OPENSSL"
[ "$packages_force_compilation" == "N" ] && pkg_result=$(package_download $pkg_name)
if [ "$pkg_result" != "success" ]; then
    url="http://www.openssl.org/source/openssl-$VER_OPENSSL.tar.gz"
    file=openssl-$VER_OPENSSL.tar.gz
    result=$(file_download --url $url --file $file --cache-dir-name downloads --check-file-size 4000000)
    if [ "$result" == "error" ]; then
        echo "Error: Unable to download $file file!"
        exit 1
    fi
fi

##
## install
##

if [ "$pkg_result" != "success" ]; then
    echo "Compile OpenSSL:"
    [ -d $INSTALL_DIR/openssl ] && rm -rf $INSTALL_DIR/openssl
    tar -zxf openssl-$VER_OPENSSL.tar.gz
    cd openssl-$VER_OPENSSL
    # SEE: http://ubuntuforums.org/showthread.php?t=1905963
    while read line; do
        echo Applying patch from $line file
        patch -p1 < $script_dir/../pkg/$package/patches/$line
    done < $script_dir/../pkg/$package/patches/series
    ./config \
        --prefix=$INSTALL_DIR/openssl \
        --openssldir=$INSTALL_DIR/openssl \
        --with-zlib-lib=$INSTALL_DIR/zlib/lib \
        --with-zlib-include=$INSTALL_DIR/zlib/include \
        shared zlib-dynamic enable-camellia \
    && make depend && make && make install && echo "OpenSSL installed successfully!"
    rm -rf $INSTALL_DIR/openssl/{private,man}
    cd ..
    echo "Strip symbols:"
    development_strip_symbols $INSTALL_DIR/openssl/bin
    development_strip_symbols $INSTALL_DIR/openssl/lib
    echo "Create package:"
    package_create $INSTALL_DIR/openssl $pkg_name
else
    echo "Install OpenSSL from package:"
    package_restore $pkg_name
fi

# check
if [ ! -f $INSTALL_DIR/openssl/bin/openssl ]; then
    echo "Error: OpenSSL has NOT been installed successfully!"
    exit 1
fi

##
## configure
##

# device specific configuration
if [ -f $script_dir/../pkg/$package/config-${DIST}-${DEVICE} ]; then
    chmod +x $script_dir/../pkg/$package/config-${DIST}-${DEVICE}
    (. $script_dir/../pkg/$package/config-${DIST}-${DEVICE})
fi

echo "Shared library dependencies for $INSTALL_DIR/openssl/bin/openssl:"
ldd $INSTALL_DIR/openssl/bin/openssl

# set files permission
chown -R root:root $INSTALL_DIR/openssl

##
## post install
##

[ -f openssl-${VER_OPENSSL}${PACKAGE_SUFFIX} ] && rm openssl-${VER_OPENSSL}${PACKAGE_SUFFIX}
[ -f openssl-$VER_OPENSSL.tar.gz ] && rm openssl-$VER_OPENSSL.tar.gz
[ -d openssl-$VER_OPENSSL ] && rm -rf openssl-$VER_OPENSSL

# save package version
package_add_version "openssl" "$VER_OPENSSL"

# add directories to create hashes
hashes_add_dir $INSTALL_DIR/openssl/bin
hashes_add_dir $INSTALL_DIR/openssl/lib

exit 0

