#!/bin/bash

################################################################################
## general routines
##

function scm_manager_start() {

   # define help
    local help=$(cat <<HEREDOC

    DESCRIPTION: Start SCM Manager application.

    PARAMETERS:
        --wait      wait for the application to start up
HEREDOC
)

    # check parameters
    if [ "$1" == "--help" ]; then
        echo -e "${help}\n"
        return
    fi

    # get parameters
    local wait=$result_neg
    while [ "$1" != "" ]; do
        case $1 in
            --wait) wait=$result_pos
                    ;;
        esac
        shift
    done

    sudo -u $scm_manager_user $scm_manager_path/bin/scm-server start

    # wait
    if [ $wait == $result_pos ]; then
        while true; do
            printf "."
            sleep 1
            local result=$(wget -T 1 -t 1 -qO- http://127.0.0.1:${scm_manager_port}/scm | grep -i 'scm manager' | wc -l)
            if [ $result -gt 0 ]; then
                printf "\n"
                break
            fi
        done
    else
        sleep 3
    fi
}

function scm_manager_stop() {

   # define help
    local help=$(cat <<HEREDOC

    DESCRIPTION: Stop SCM Manager application.
HEREDOC
)

    # check parameters
    if [ "$1" == "--help" ]; then
        echo -e "${help}\n"
        return
    fi

    sudo -u $scm_manager_user $scm_manager_path/bin/scm-server stop
    sleep 3

    # kill it if still running
    if [ $(scm_manager_is_running) == $result_pos ]; then
        local pid=$(ps aux | grep -v grep | grep $scm_manager_path | awk '{ print $2 }')
        kill -9 $pid > /dev/null 2>&1
    fi
}

function scm_manager_restart() {

   # define help
    local help=$(cat <<HEREDOC

    DESCRIPTION: Restart SCM Manager application.

    PARAMETERS:
        --wait      wait for the application to restart
HEREDOC
)

    # check parameters
    if [ "$1" == "--help" ]; then
        echo -e "${help}\n"
        return
    fi

    scm_manager_stop
    sleep 3
    scm_manager_start $*
}

function scm_manager_is_running() {

   # define help
    local help=$(cat <<HEREDOC

    DESCRIPTION: Check if SCM Manager application is running.
HEREDOC
)

    # check parameters
    if [ "$1" == "--help" ]; then
        echo -e "${help}\n"
        return
    fi

    local count=$(ps aux | grep -v grep | grep $scm_manager_path | wc -l)
    if [ $count -gt 0 ]; then
        echo $result_pos
    else
        echo $result_neg
    fi
}
