#!/bin/bash

source ~/.shell-fusion/shell-fusion.sh 2> /dev/null
[ $? != 0 ] && source /usr/local/shell-fusion/shell-fusion.sh 2> /dev/null

source $config_script

# The following variables need to be set:
#   NAME
#   RUN_AS_USER

function start {

    if [ $DIST == "macosx" ]; then
        sudo launchctl load -w /System/Library/LaunchDaemons/$NAME.plist
    else
        :
    fi
}

function stop {

    if [ $DIST == "macosx" ]; then
        sudo launchctl unload -w /System/Library/LaunchDaemons/$NAME.plist
    else
        :
    fi
}

function restart {

    stop
    sleep 1
    start
}

function status {

    sudo -H -u $RUN_AS_USER bash -c "$(get_program_dir)/daemon status"
}

function usage {

    echo "Usage: $(basename -- "$0") {start|stop|restart|status}"
}

function get_program_dir {

    local source="${BASH_SOURCE[0]}"

    while [ -h "$source" ]; do
        DIR="$(cd -P "$(dirname "$source")" && pwd)"
        source="$(readlink "$source")"
        [[ $source != /* ]] && source="$DIR/$source"
    done
    local dir="$(cd -P "$(dirname "$source")" && pwd)"

    echo $dir
}

# check variables
if [ -z "$NAME" ] || [ -z "$RUN_AS_USER" ]; then
    echo "Configuration script does not set required variables"
    exit 1
fi

case $1 in
    start)      start
                ;;
    stop)       stop
                ;;
    restart)    restart
                ;;
    status)     status
                ;;
    *)          usage
                ;;
esac

exit 0
