#!/bin/bash

##
## download packages
##

if [ "$do_not_use_cached_updates" == "N" ]; then
    result=$(file_download --file $DEVICE_NAME.tar.gz --cache-dir-name updates --do-not-cache)
    if [ "$result" == "success" ]; then
        mv $DEVICE_NAME.tar.gz /var/cache/apt/archives
        cd /var/cache/apt/archives
        tar -zxf $DEVICE_NAME.tar.gz
        rm $DEVICE_NAME.tar.gz
    fi
fi

##
## manage packages
##

#do-release-upgrade -d

# exclude packages from system update (to remove exclusion use 'echo ${PACKAGE} install | dpkg --set-selections')
(
    echo postfix hold
) | dpkg --set-selections

# run system update
DEBIAN_FRONTEND="noninteractive"
apt-get --yes update
apt-get --yes --force-yes upgrade
apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade

# install
apt-get --yes --force-yes --ignore-missing --no-install-recommends install \
    apparmor \
    apt-file \
    apt-show-versions \
    apt-utils \
    autoconf \
    autogen \
    automake \
    autopoint \
    bc \
    bison \
    build-essential \
    bzr \
    chkrootkit \
    cmake \
    debootstrap \
    dialog \
    dnsutils \
    expect \
    exuberant-ctags \
    fail2ban \
    fakeroot \
    gawk \
    genisoimage \
    gettext \
    host \
    iftop \
    kernel-package \
    kpartx \
    libbz2-dev \
    libcap2-bin \
    libcap-dev \
    libcurl4-openssl-dev \
    libdb-dev \
    libexpat1-dev \
    libfreetype6 \
    libfreetype6-dev \
    libjpeg62-dev \
    liblua50-dev \
    liblua5.1-0-dev \
    liblualib50-dev \
    libmcrypt-dev \
    libmhash-dev \
    libncurses5-dev \
    libpcre3-dev \
    libpng12-dev \
    libsqlite0-dev \
    libsqlite3-dev \
    libssl-dev \
    libtool \
    libwrap0-dev \
    libxml2-dev \
    lshw \
    lsof \
    lzop \
    mercurial \
    nano \
    nmap \
    pkg-config \
    python-software-properties \
    re2c \
    rkhunter \
    rsync \
    schroot \
    scons \
    sqlite3 \
    strace \
    subversion \
    syslinux \
    sysstat \
    tcpdump \
    traceroute \
    unzip \
    update-manager-core \
    vim \
    xemacs21-bin \
    xorriso \
    whois
if [ "$USE_BRIDGED_NETWORK" == "Y" ]; then
    apt-get --yes --force-yes --ignore-missing --no-install-recommends install \
        bridge-utils
fi
if [ $(role_has "virtual") == "yes" ] && [ $(role_has "vbox") == "yes" ]; then
    apt-get --yes --force-yes --ignore-missing --no-install-recommends install \
        virtualbox-guest-utils virtualbox-guest-dkms virtualbox-guest-additions virtualbox-guest-additions-iso
fi

# remove
apt-get --yes --force-yes remove \
    ufw

# clean
apt-get autoremove --yes --force-yes
apt-get autoclean --yes --force-yes

# build database
apt-file update

# fix libraries
fix_common_libraries

exit 0

