#!/bin/bash

##
## download
##

url="http://www.java.net/download/jdk${VER_OPENJDK_NUMBER}u${VER_OPENJDK_UPDATE}/archive/${VER_OPENJDK_BUILD}/binaries/jdk-${VER_OPENJDK_NUMBER}u${VER_OPENJDK_UPDATE}-ea-bin-${VER_OPENJDK_BUILD}-linux-x64-${VER_OPENJDK_DATE}.tar.gz"
file=jdk-${VER_OPENJDK_NUMBER}u${VER_OPENJDK_UPDATE}-ea-bin-${VER_OPENJDK_BUILD}-linux-x64-${VER_OPENJDK_DATE}.tar.gz
result=$(file_download --url $url --file $file --cache-dir-name downloads --check-file-size 50000000)
if [ "$result" == "error" ]; then
    echo "Error: Unable to download $file file!"
    exit 1
fi

##
## install
##

echo "Installing OpenJDK:"
[ -d $INSTALL_DIR/openjdk ] && rm -rf $INSTALL_DIR/openjdk
tar -zxf $file
openjdk_dir=$(ls -d -- */ | grep jdk1.${VER_OPENJDK_NUMBER})
mv $openjdk_dir $INSTALL_DIR/openjdk
rm -rf $INSTALL_DIR/openjdk/man

# check
if [ ! -x $INSTALL_DIR/openjdk/bin/javac ]; then
    echo "Error: OpenJDK has NOT been installed successfully!"
    exit 1
else
    echo "OpenJDK installed successfully!"
fi

##
## configure
##

# set files permission
chown -R root:root $INSTALL_DIR/openjdk

##
## post install
##

[ -f $file ] && rm $file

# save package version
package_add_version "openjdk" "$VER_OPENJDK"

# add directories to create hashes
hashes_add_dir $INSTALL_DIR/openjdk/bin
hashes_add_dir $INSTALL_DIR/openjdk/lib
hashes_add_dir $INSTALL_DIR/openjdk/jre/bin
hashes_add_dir $INSTALL_DIR/openjdk/jre/lib

exit 0

