
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `variable`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `variable` (
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT 'The name of the variable.',
  `value` longblob NOT NULL COMMENT 'The value of the variable.',
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Named variable/value pairs created by Drupal core or any...';
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `variable` WRITE;
/*!40000 ALTER TABLE `variable` DISABLE KEYS */;
INSERT INTO `variable` VALUES ('additional_settings__active_tab_news','s:15:\"edit-xmlsitemap\";');
INSERT INTO `variable` VALUES ('admin_theme','s:5:\"seven\";');
INSERT INTO `variable` VALUES ('anonymous','s:6:\"Anonim\";');
INSERT INTO `variable` VALUES ('array_filter','b:1;');
INSERT INTO `variable` VALUES ('block_cache','i:0;');
INSERT INTO `variable` VALUES ('cache','i:0;');
INSERT INTO `variable` VALUES ('cache_lifetime','s:1:\"0\";');
INSERT INTO `variable` VALUES ('clean_url','s:1:\"1\";');
INSERT INTO `variable` VALUES ('comment_anonymous_news','i:0;');
INSERT INTO `variable` VALUES ('comment_default_mode_news','i:1;');
INSERT INTO `variable` VALUES ('comment_default_per_page_news','s:2:\"50\";');
INSERT INTO `variable` VALUES ('comment_form_location_news','i:1;');
INSERT INTO `variable` VALUES ('comment_news','s:1:\"2\";');
INSERT INTO `variable` VALUES ('comment_page','i:0;');
INSERT INTO `variable` VALUES ('comment_preview_news','s:1:\"1\";');
INSERT INTO `variable` VALUES ('comment_subject_field_news','i:1;');
INSERT INTO `variable` VALUES ('configurable_timezones','i:1;');
INSERT INTO `variable` VALUES ('cron_key','s:43:\"HU8p45qOKlLdEnR-Tliz71gCAMqRIdc4FP0wn5jDQvY\";');
INSERT INTO `variable` VALUES ('cron_last','i:1339082531;');
INSERT INTO `variable` VALUES ('css_js_query_string','s:6:\"m596uq\";');
INSERT INTO `variable` VALUES ('ctools_last_cron','i:1339046306;');
INSERT INTO `variable` VALUES ('date_default_timezone','s:13:\"Europe/Warsaw\";');
INSERT INTO `variable` VALUES ('date_first_day','s:1:\"1\";');
INSERT INTO `variable` VALUES ('date_format_long','s:15:\"l, j F, Y - H:i\";');
INSERT INTO `variable` VALUES ('date_format_medium','s:14:\"D, d/m/Y - H:i\";');
INSERT INTO `variable` VALUES ('date_format_short','s:11:\"d/m/Y - H:i\";');
INSERT INTO `variable` VALUES ('dblog_row_limit','s:1:\"0\";');
INSERT INTO `variable` VALUES ('default_nodes_main','s:2:\"10\";');
INSERT INTO `variable` VALUES ('drupal_http_request_fails','b:0;');
INSERT INTO `variable` VALUES ('drupal_private_key','s:43:\"VL9cvPezd03is084MuXmZGgyEchELaLOWxvSZCNYLCg\";');
INSERT INTO `variable` VALUES ('email__active_tab','s:24:\"edit-email-admin-created\";');
INSERT INTO `variable` VALUES ('empty_timezone_message','i:1;');
INSERT INTO `variable` VALUES ('error_level','s:1:\"2\";');
INSERT INTO `variable` VALUES ('features_ignored_orphans','a:0:{}');
INSERT INTO `variable` VALUES ('feed_default_items','s:2:\"10\";');
INSERT INTO `variable` VALUES ('feed_description','s:0:\"\";');
INSERT INTO `variable` VALUES ('feed_item_length','s:6:\"teaser\";');
INSERT INTO `variable` VALUES ('field_bundle_settings_node__news','a:2:{s:10:\"view_modes\";a:6:{s:6:\"teaser\";a:1:{s:15:\"custom_settings\";b:1;}s:4:\"full\";a:1:{s:15:\"custom_settings\";b:0;}s:3:\"rss\";a:1:{s:15:\"custom_settings\";b:1;}s:12:\"search_index\";a:1:{s:15:\"custom_settings\";b:0;}s:13:\"search_result\";a:1:{s:15:\"custom_settings\";b:0;}s:5:\"token\";a:1:{s:15:\"custom_settings\";b:0;}}s:12:\"extra_fields\";a:2:{s:4:\"form\";a:3:{s:5:\"title\";a:1:{s:6:\"weight\";s:1:\"1\";}s:4:\"path\";a:1:{s:6:\"weight\";s:2:\"99\";}s:10:\"xmlsitemap\";a:1:{s:6:\"weight\";s:2:\"99\";}}s:7:\"display\";a:0:{}}}');
INSERT INTO `variable` VALUES ('file_temporary_path','s:4:\"/tmp\";');
INSERT INTO `variable` VALUES ('filter_fallback_format','s:10:\"plain_text\";');
INSERT INTO `variable` VALUES ('fusion_starter_responsive_css','s:34:\"fusion_starter.responsive.grid.css\";');
INSERT INTO `variable` VALUES ('fusion_starter_responsive_path','s:15:\"public://fusion\";');
INSERT INTO `variable` VALUES ('googleanalytics_account','s:13:\"UA-31434984-1\";');
INSERT INTO `variable` VALUES ('googleanalytics_cache','i:0;');
INSERT INTO `variable` VALUES ('googleanalytics_codesnippet_after','s:0:\"\";');
INSERT INTO `variable` VALUES ('googleanalytics_codesnippet_before','s:0:\"\";');
INSERT INTO `variable` VALUES ('googleanalytics_cross_domains','s:0:\"\";');
INSERT INTO `variable` VALUES ('googleanalytics_custom','s:1:\"0\";');
INSERT INTO `variable` VALUES ('googleanalytics_custom_var','a:1:{s:5:\"slots\";a:5:{i:1;a:4:{s:4:\"slot\";i:1;s:4:\"name\";s:0:\"\";s:5:\"value\";s:0:\"\";s:5:\"scope\";s:1:\"3\";}i:2;a:4:{s:4:\"slot\";i:2;s:4:\"name\";s:0:\"\";s:5:\"value\";s:0:\"\";s:5:\"scope\";s:1:\"3\";}i:3;a:4:{s:4:\"slot\";i:3;s:4:\"name\";s:0:\"\";s:5:\"value\";s:0:\"\";s:5:\"scope\";s:1:\"3\";}i:4;a:4:{s:4:\"slot\";i:4;s:4:\"name\";s:0:\"\";s:5:\"value\";s:0:\"\";s:5:\"scope\";s:1:\"3\";}i:5;a:4:{s:4:\"slot\";i:5;s:4:\"name\";s:0:\"\";s:5:\"value\";s:0:\"\";s:5:\"scope\";s:1:\"3\";}}}');
INSERT INTO `variable` VALUES ('googleanalytics_domain_mode','s:1:\"0\";');
INSERT INTO `variable` VALUES ('googleanalytics_js_scope','s:6:\"header\";');
INSERT INTO `variable` VALUES ('googleanalytics_pages','s:52:\"admin\r\nadmin/*\r\nbatch\r\nnode/add*\r\nnode/*/*\r\nuser/*/*\";');
INSERT INTO `variable` VALUES ('googleanalytics_privacy_donottrack','i:1;');
INSERT INTO `variable` VALUES ('googleanalytics_roles','a:3:{i:1;s:1:\"1\";i:2;s:1:\"2\";i:3;i:0;}');
INSERT INTO `variable` VALUES ('googleanalytics_site_search','i:0;');
INSERT INTO `variable` VALUES ('googleanalytics_trackadsense','i:0;');
INSERT INTO `variable` VALUES ('googleanalytics_tracker_anonymizeip','i:0;');
INSERT INTO `variable` VALUES ('googleanalytics_trackfiles','i:1;');
INSERT INTO `variable` VALUES ('googleanalytics_trackfiles_extensions','s:195:\"7z|aac|arc|arj|asf|asx|avi|bin|csv|doc|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|msi|msp|pdf|phps|png|ppt|qtm?|ra(m|r)?|sea|sit|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls|xml|z|zip\";');
INSERT INTO `variable` VALUES ('googleanalytics_trackmailto','i:1;');
INSERT INTO `variable` VALUES ('googleanalytics_trackoutbound','i:1;');
INSERT INTO `variable` VALUES ('googleanalytics_trackoutboundaspageview','i:0;');
INSERT INTO `variable` VALUES ('googleanalytics_visibility_pages','s:1:\"0\";');
INSERT INTO `variable` VALUES ('googleanalytics_visibility_roles','s:1:\"0\";');
INSERT INTO `variable` VALUES ('image_toolkit','s:2:\"gd\";');
INSERT INTO `variable` VALUES ('install_profile','s:8:\"standard\";');
INSERT INTO `variable` VALUES ('install_task','s:4:\"done\";');
INSERT INTO `variable` VALUES ('install_time','i:1335904363;');
INSERT INTO `variable` VALUES ('language_content_type_news','s:1:\"0\";');
INSERT INTO `variable` VALUES ('language_count','i:2;');
INSERT INTO `variable` VALUES ('language_default','O:8:\"stdClass\":11:{s:8:\"language\";s:2:\"pl\";s:4:\"name\";s:6:\"Polish\";s:6:\"native\";s:6:\"Polski\";s:9:\"direction\";s:1:\"0\";s:7:\"enabled\";s:1:\"1\";s:7:\"plurals\";s:1:\"3\";s:7:\"formula\";s:85:\"(($n==1)?(0):((((($n%10)>=2)&&(($n%10)<=4))&&((($n%100)<10)||(($n%100)>=20)))?(1):2))\";s:6:\"domain\";s:0:\"\";s:6:\"prefix\";s:2:\"pl\";s:6:\"weight\";s:1:\"0\";s:10:\"javascript\";s:43:\"SGPM4K7i_SfYk8IdUUNf9MXk58lIIv_Zp5b6JbfP-7Q\";}');
INSERT INTO `variable` VALUES ('language_negotiation_language','a:0:{}');
INSERT INTO `variable` VALUES ('language_negotiation_language_content','a:1:{s:16:\"locale-interface\";a:2:{s:9:\"callbacks\";a:1:{s:8:\"language\";s:30:\"locale_language_from_interface\";}s:4:\"file\";s:19:\"includes/locale.inc\";}}');
INSERT INTO `variable` VALUES ('language_negotiation_language_url','a:2:{s:10:\"locale-url\";a:2:{s:9:\"callbacks\";a:3:{s:8:\"language\";s:24:\"locale_language_from_url\";s:8:\"switcher\";s:28:\"locale_language_switcher_url\";s:11:\"url_rewrite\";s:31:\"locale_language_url_rewrite_url\";}s:4:\"file\";s:19:\"includes/locale.inc\";}s:19:\"locale-url-fallback\";a:2:{s:9:\"callbacks\";a:1:{s:8:\"language\";s:28:\"locale_language_url_fallback\";}s:4:\"file\";s:19:\"includes/locale.inc\";}}');
INSERT INTO `variable` VALUES ('language_types','a:3:{s:8:\"language\";b:1;s:16:\"language_content\";b:0;s:12:\"language_url\";b:0;}');
INSERT INTO `variable` VALUES ('maintenance_mode','i:0;');
INSERT INTO `variable` VALUES ('maintenance_mode_message','s:121:\"Na zeroday.pl mamy w tej chwili przerwę techniczną. Powinna się ona wkrótce skończyć. Dziękujemy za cierpliwość.\";');
INSERT INTO `variable` VALUES ('menu_expanded','a:0:{}');
INSERT INTO `variable` VALUES ('menu_masks','a:40:{i:0;i:501;i:1;i:493;i:2;i:251;i:3;i:250;i:4;i:247;i:5;i:246;i:6;i:245;i:7;i:125;i:8;i:124;i:9;i:123;i:10;i:122;i:11;i:121;i:12;i:117;i:13;i:63;i:14;i:62;i:15;i:61;i:16;i:60;i:17;i:59;i:18;i:58;i:19;i:45;i:20;i:44;i:21;i:31;i:22;i:30;i:23;i:29;i:24;i:28;i:25;i:24;i:26;i:22;i:27;i:21;i:28;i:15;i:29;i:14;i:30;i:13;i:31;i:11;i:32;i:10;i:33;i:7;i:34;i:6;i:35;i:5;i:36;i:4;i:37;i:3;i:38;i:2;i:39;i:1;}');
INSERT INTO `variable` VALUES ('menu_options_news','a:1:{i:0;s:9:\"main-menu\";}');
INSERT INTO `variable` VALUES ('menu_parent_news','s:11:\"main-menu:0\";');
INSERT INTO `variable` VALUES ('node_admin_theme','s:1:\"1\";');
INSERT INTO `variable` VALUES ('node_cron_last','s:10:\"1339001085\";');
INSERT INTO `variable` VALUES ('node_options_news','a:2:{i:0;s:6:\"status\";i:1;s:7:\"promote\";}');
INSERT INTO `variable` VALUES ('node_options_page','a:1:{i:0;s:6:\"status\";}');
INSERT INTO `variable` VALUES ('node_preview_news','s:1:\"2\";');
INSERT INTO `variable` VALUES ('node_submitted_news','i:1;');
INSERT INTO `variable` VALUES ('node_submitted_page','b:0;');
INSERT INTO `variable` VALUES ('page_cache_maximum_age','s:1:\"0\";');
INSERT INTO `variable` VALUES ('page_compression','i:1;');
INSERT INTO `variable` VALUES ('pathauto_blog_pattern','s:17:\"blogs/[user:name]\";');
INSERT INTO `variable` VALUES ('pathauto_forum_pattern','s:29:\"[term:vocabulary]/[term:name]\";');
INSERT INTO `variable` VALUES ('pathauto_node_article_pattern','s:20:\"artykul/[node:title]\";');
INSERT INTO `variable` VALUES ('pathauto_node_page_pattern','s:0:\"\";');
INSERT INTO `variable` VALUES ('pathauto_node_pattern','s:12:\"[node:title]\";');
INSERT INTO `variable` VALUES ('pathauto_punctuation_hyphen','i:1;');
INSERT INTO `variable` VALUES ('pathauto_taxonomy_term_pattern','s:29:\"[term:vocabulary]/[term:name]\";');
INSERT INTO `variable` VALUES ('pathauto_taxonomy_term_tags_pattern','s:0:\"\";');
INSERT INTO `variable` VALUES ('pathauto_user_pattern','s:22:\"uzytkownik/[user:name]\";');
INSERT INTO `variable` VALUES ('path_alias_whitelist','a:3:{s:4:\"node\";b:1;s:8:\"taxonomy\";b:1;s:4:\"user\";b:1;}');
INSERT INTO `variable` VALUES ('preprocess_css','i:1;');
INSERT INTO `variable` VALUES ('preprocess_js','i:1;');
INSERT INTO `variable` VALUES ('save_continue_news','s:21:\"Zachowaj i dodaj pola\";');
INSERT INTO `variable` VALUES ('site_403','s:0:\"\";');
INSERT INTO `variable` VALUES ('site_404','s:0:\"\";');
INSERT INTO `variable` VALUES ('site_default_country','s:2:\"PL\";');
INSERT INTO `variable` VALUES ('site_frontpage','s:4:\"node\";');
INSERT INTO `variable` VALUES ('site_mail','s:16:\"admin@zeroday.pl\";');
INSERT INTO `variable` VALUES ('site_name','s:10:\"zeroday.pl\";');
INSERT INTO `variable` VALUES ('site_slogan','s:21:\"The game... has begun\";');
INSERT INTO `variable` VALUES ('theme_default','s:14:\"fusion_starter\";');
INSERT INTO `variable` VALUES ('tracking__active_tab','s:12:\"edit-privacy\";');
INSERT INTO `variable` VALUES ('update_last_check','i:1339082575;');
INSERT INTO `variable` VALUES ('update_notify_emails','a:1:{i:0;s:16:\"admin@zeroday.pl\";}');
INSERT INTO `variable` VALUES ('user_admin_role','s:1:\"3\";');
INSERT INTO `variable` VALUES ('user_cancel_method','s:17:\"user_cancel_block\";');
INSERT INTO `variable` VALUES ('user_default_timezone','s:1:\"0\";');
INSERT INTO `variable` VALUES ('user_email_verification','i:1;');
INSERT INTO `variable` VALUES ('user_mail_cancel_confirm_body','s:396:\"[user:name],\r\n\r\nZostała uruchomiona procedura anulowania Twojego konta na stronie  [site:name].\r\n\r\nMożesz anulować swoje konto na stronie [site:url-brief] klikając poniższy odnośnik bądź kopiując go w pole adresu przeglądarki:\r\n\r\n[user:cancel-url]\r\n\r\nUWAGA: anulowanie konta jest operacją nieodwracalną.\r\n\r\nOdnośnik straci ważność po jednym dniu.\r\n\r\n-- redakcja strony [site:name]\";');
INSERT INTO `variable` VALUES ('user_mail_cancel_confirm_subject','s:61:\"Prośba o usunięcie konta [user:name] na stronie [site:name]\";');
INSERT INTO `variable` VALUES ('user_mail_password_reset_body','s:407:\"[user:name],\r\n\r\nW serwisie [site:name] została uruchomiona procedura resetowania twojego hasła.\r\n\r\nMożesz się zalogować klikając poniższy odnośnik bądź kopiując go w pole adresu przeglądarki:\r\n\r\n[user:one-time-login-url]\r\n\r\nOdnośnik może zostać użyty tylko raz a jego użycie umożliwi wpisanie własnego hasła. Odnośnik straci ważność po jednym dniu.\r\n\r\n--  redakcja strony [site:name]\";');
INSERT INTO `variable` VALUES ('user_mail_password_reset_subject','s:70:\"Odzyskiwanie hasła dla użytkownika [user:name] ze strony [site:name]\";');
INSERT INTO `variable` VALUES ('user_mail_register_admin_created_body','s:527:\"[user:name],\r\n\r\nAdministrator strony [site:name] utworzył dla Ciebie konto. Możesz się zalogować klikając poniższy odnośnik bądź kopiując go w pole adresu przeglądarki:\r\n\r\n[user:one-time-login-url]\r\n\r\nOdnośnik może zostać użyty tylko raz a jego użycie umożliwi wpisanie własnego hasła.\r\n\r\nPo ustawieniu swojego hasła będzie można zalogować się do serwisu pod adresem [site:login-url] wykorzystując poniższe dane:\r\n\r\nnazwa konta: [user:name]\r\nhasło: Ustawione hasło\r\n\r\n--  redakcja strony [site:name]\";');
INSERT INTO `variable` VALUES ('user_mail_register_admin_created_subject','s:63:\"Administrator utworzył dla ciebie konto na stronie [site:name]\";');
INSERT INTO `variable` VALUES ('user_mail_register_no_approval_required_body','s:510:\"[user:name],\r\n\r\nDziękujemy za rejestrację na [site:name]. Możesz się zalogować klikając poniższy odnośnik bądź kopiując go w pole adresu przeglądarki:\r\n\r\n[user:one-time-login-url]\r\n\r\nOdnośnik może zostać użyty tylko raz a jego użycie umożliwi wpisanie własnego hasła.\r\n\r\nPo ustawieniu swojego hasła będzie można zalogować się do serwisu pod adresem [site:login-url] wykorzystując poniższe dane:\r\n\r\nnazwa konta: [user:name]\r\nhasło: Ustawione hasło\r\n\r\n--  redakcja strony [site:name]\";');
INSERT INTO `variable` VALUES ('user_mail_register_no_approval_required_subject','s:52:\"Szczegóły konta [user:name] na stronie [site:name]\";');
INSERT INTO `variable` VALUES ('user_mail_register_pending_approval_body','s:263:\"[user:name],\r\n\r\nDziękujemy za rejestrację na stronie [site:name]. Twoje konto oczekuje na aprobatę administratora. W chwili zakończenia tego procesu otrzymasz e-mail zawierający dane potrzebne do zalogowania się do serwisu.\r\n\r\n-- redakcja strony [site:name]\";');
INSERT INTO `variable` VALUES ('user_mail_register_pending_approval_subject','s:104:\"Szczegóły konta [user:name] na stronie [site:name] (oczekiwanie na zatwierdzenie przez administratora)\";');
INSERT INTO `variable` VALUES ('user_mail_status_activated_body','s:522:\"[user:name],\r\n\r\nTwoje konto na stronie [site:name] zostało aktywowane. Możesz się zalogować klikając poniższy odnośnik bądź kopiując go w pole adresu przeglądarki:\r\n\r\n[user:one-time-login-url]\r\n\r\nOdnośnik może zostać użyty tylko raz a jego użycie umożliwi wpisanie własnego hasła.\r\n\r\nPo ustawieniu swojego hasła będzie można zalogować się do serwisu pod adresem [site:login-url] wykorzystując poniższe dane:\r\n\r\nnazwa konta: [user:name]\r\nhasło: Ustawione hasło\r\n\r\n--  redakcja strony [site:name]\";');
INSERT INTO `variable` VALUES ('user_mail_status_activated_notify','i:1;');
INSERT INTO `variable` VALUES ('user_mail_status_activated_subject','s:67:\"Szczegóły konta [user:name] na stronie [site:name] (zatwierdzony)\";');
INSERT INTO `variable` VALUES ('user_mail_status_blocked_body','s:106:\"[user:name],\r\n\r\nTwoje konto na stronie [site:name] zostało zablokowane.\r\n\r\n-- redakcja strony [site:name]\";');
INSERT INTO `variable` VALUES ('user_mail_status_blocked_notify','i:0;');
INSERT INTO `variable` VALUES ('user_mail_status_blocked_subject','s:66:\"Szczegóły konta [user:name] na stronie [site:name] (zablokowany)\";');
INSERT INTO `variable` VALUES ('user_mail_status_canceled_body','s:104:\"[user:name],\r\n\r\nTwoje konto na stronie [site:name] zostało anulowane.\r\n\r\n-- redakcja strony [site:name]\";');
INSERT INTO `variable` VALUES ('user_mail_status_canceled_notify','i:0;');
INSERT INTO `variable` VALUES ('user_mail_status_canceled_subject','s:64:\"Szczegóły konta [user:name] na stronie [site:name] (usunięty)\";');
INSERT INTO `variable` VALUES ('user_pictures','i:1;');
INSERT INTO `variable` VALUES ('user_picture_default','s:0:\"\";');
INSERT INTO `variable` VALUES ('user_picture_dimensions','s:7:\"256x256\";');
INSERT INTO `variable` VALUES ('user_picture_file_size','s:3:\"256\";');
INSERT INTO `variable` VALUES ('user_picture_guidelines','s:0:\"\";');
INSERT INTO `variable` VALUES ('user_picture_path','s:8:\"pictures\";');
INSERT INTO `variable` VALUES ('user_picture_style','s:9:\"thumbnail\";');
INSERT INTO `variable` VALUES ('user_register','s:1:\"0\";');
INSERT INTO `variable` VALUES ('user_signatures','i:1;');
INSERT INTO `variable` VALUES ('xmlsitemap_base_url','s:17:\"http://zeroday.pl\";');
INSERT INTO `variable` VALUES ('xmlsitemap_batch_limit','s:3:\"100\";');
INSERT INTO `variable` VALUES ('xmlsitemap_chunk_size','s:4:\"auto\";');
INSERT INTO `variable` VALUES ('xmlsitemap_developer_mode','i:0;');
INSERT INTO `variable` VALUES ('xmlsitemap_engines_custom_urls','s:0:\"\";');
INSERT INTO `variable` VALUES ('xmlsitemap_engines_engines','a:2:{i:0;s:4:\"bing\";i:1;s:6:\"google\";}');
INSERT INTO `variable` VALUES ('xmlsitemap_engines_minimum_lifetime','s:5:\"86400\";');
INSERT INTO `variable` VALUES ('xmlsitemap_engines_submit_last','i:1339082531;');
INSERT INTO `variable` VALUES ('xmlsitemap_engines_submit_updated','i:1;');
INSERT INTO `variable` VALUES ('xmlsitemap_frontpage_changefreq','s:5:\"86400\";');
INSERT INTO `variable` VALUES ('xmlsitemap_frontpage_priority','s:3:\"1.0\";');
INSERT INTO `variable` VALUES ('xmlsitemap_generated_last','i:1339004152;');
INSERT INTO `variable` VALUES ('xmlsitemap_lastmod_format','s:1:\"c\";');
INSERT INTO `variable` VALUES ('xmlsitemap_minimum_lifetime','s:1:\"0\";');
INSERT INTO `variable` VALUES ('xmlsitemap_path','s:10:\"xmlsitemap\";');
INSERT INTO `variable` VALUES ('xmlsitemap_prefetch_aliases','i:1;');
INSERT INTO `variable` VALUES ('xmlsitemap_regenerate_needed','b:0;');
INSERT INTO `variable` VALUES ('xmlsitemap_settings_node_news','a:2:{s:6:\"status\";s:1:\"1\";s:8:\"priority\";s:3:\"0.5\";}');
INSERT INTO `variable` VALUES ('xmlsitemap_settings__active_tab','s:14:\"edit-frontpage\";');
INSERT INTO `variable` VALUES ('xmlsitemap_xsl','i:1;');
/*!40000 ALTER TABLE `variable` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

