#!/bin/bash

##
## include
##

. $package_dir/common

##
## functions
##

function php_fpm_install() {

    # set version
    php_fpm_ver=$1
    # set variables
    php_fpm_set_version_dependent_variables
    # download package
    php_fpm_download_package

    # install package
    if [ "$pkg_result" != "success" ]; then
        echo "Build $package $php_fpm_ver":
        . $package_dir/build
        echo "Create package:"
        package_create $php_fpm_install_dir $pkg_name
    else
        echo "Install $package $php_fpm_ver from package:"
        package_restore $pkg_name --dir $INSTALL_DIR/$package
    fi
    # check installtion
    if [ ! -f $php_fpm_install_dir/bin/php-fpm ]; then
        echo "Error: $package $php_fpm_ver has NOT been installed successfully!"
        exit 1
    fi

    # configure service
    php_fpm_configure_service
    # set file permissions
    php_fpm_set_file_permissions
    # post install
    php_fpm_post_install
    # print info
    php_fpm_print_info
}

##
## main
##

mkdir -p $INSTALL_DIR/php-fpm
for php_fpm_ver in $VER_PHP_FPM_LIST; do
    php_fpm_install $php_fpm_ver
done

exit 0

