#!/bin/bash

##
## download
##

pkg_name="mongodb-$VER_MONGODB"
[ "$packages_force_compilation" == "N" ] && pkg_result=$(package_download $pkg_name)
if [ "$pkg_result" != "success" ]; then
    url="http://downloads.mongodb.org/src/mongodb-src-r$VER_MONGODB.tar.gz"
    file=mongodb-src-r$VER_MONGODB.tar.gz
    result=$(file_download --url $url --file $file --cache-dir-name downloads --check-file-size 10000000)
    if [ "$result" == "error" ]; then
        echo "Error: Unable to download $file file!"
        exit 1
    fi
fi

##
## install
##

if [ "$pkg_result" != "success" ]; then
    echo "Compile mongodb:"
    [ -d $INSTALL_DIR/mongodb ] && rm -rf $INSTALL_DIR/mongodb
    tar -zxf mongodb-src-r$VER_MONGODB.tar.gz
    cd mongodb-src-r$VER_MONGODB
    scons all && scons --prefix=$INSTALL_DIR/mongodb install && echo "mongodb installed successfully!"
    cd ..
    echo "Strip symbols:"
    development_strip_symbols $INSTALL_DIR/mongodb/bin
    development_strip_symbols $INSTALL_DIR/mongodb/lib
    echo "Create package:"
    package_create $INSTALL_DIR/mongodb $pkg_name
else
    echo "Install mongodb from package:"
    package_restore $pkg_name
fi

# check
if [ ! -f $INSTALL_DIR/mongodb/bin/mongod ]; then
    echo "Error: mongodb has NOT been installed successfully!"
    exit 1
fi

##
## configure
##

echo "Shared library dependencies for $INSTALL_DIR/mongodb/bin/mongod:"
ldd $INSTALL_DIR/mongodb/bin/mongod

# set files permission
chown -R root:root $INSTALL_DIR/mongodb

##
## post install
##

[ -f mongodb-src-r$VER_MONGODB.tar.gz ] && rm mongodb-src-r$VER_MONGODB.tar.gz
[ -d mongodb-src-r$VER_MONGODB ] && rm -rf mongodb-src-r$VER_MONGODB

# save package version
package_add_version "mongodb" "$VER_MONGODB"

# add directories to create hashes
hashes_add_dir $INSTALL_DIR/mongodb/bin
hashes_add_dir $INSTALL_DIR/mongodb/lib

exit 0

