#!/bin/bash
#
# Global variables for the installation process, common for all projects. These
# are variables likely to be changed and are modified by the build script.

# operating system codename
CODENAME=$(lsb_release -a | grep Codename | awk '{ print $2 }')

# organisation details
COMMON_NAME=""
DOMAIN=""

# admin details
ADMIN_NAME=""
ADMIN_MAIL=""

# system details
SYSTEM_NAME=""
SYSTEM_LOCATION=""
SYSTEM_TYPE=""
ROLE_NAME=""
ROLE_ID="$(role_name_to_id $ROLE_NAME)"
ASPECT_NAME=""
ASPECT_ID="$(aspect_name_to_id $ASPECT_NAME)"

# regular network settings
IP_ADDRESS=""
IP_ADDRESS1=""
IP_ADDRESS2=""
IP_ADDRESS3=""
IP_ADDRESS4=""
NETMASK=""
NETWORK=""
BROADCAST=""
GATEWAY=""
DNS_NAMESERVER1=""
DNS_NAMESERVER2=""
DNS_NAMESERVER3=""
DNS_NAMESERVER4=""
DNS_NAMESERVERS="$(trim "$DNS_NAMESERVER1 $DNS_NAMESERVER2 $DNS_NAMESERVER3 $DNS_NAMESERVER4")"
DNS_SEARCH=""
USE_BRIDGED_NETWORK=""

# vpn network settings
VPN_SERVER_FQDN=""
VPN_SERVER_IP=""
VPN_NETWORK=""
VPN_NETMASK=""
VPN_IP_ADDRESS=""

# local download alternative
if [[ "$IP_ADDRESS" != 192.168.* ]]; then
    LOCAL_DOWNLOAD_USER=""
    LOCAL_DOWNLOAD_PASS=""
    LOCAL_DOWNLOAD_URL=""
else
    LOCAL_DOWNLOAD_USER="user"
    LOCAL_DOWNLOAD_PASS="pass"
    LOCAL_DOWNLOAD_URL="ftp://192.168.?.?/downloads"
fi

# online download alternative
ONLINE_DOWNLOAD_USER=""
ONLINE_DOWNLOAD_PASS=""
ONLINE_DOWNLOAD_URL="http://dl.dropbox.com/u/?/?"

################################################################################
## include role specific variables
##

[ -f $SHELLOS_DIR/sbin/variables.$ROLE_NAME ] && \
    source $SHELLOS_DIR/sbin/variables.$ROLE_NAME

################################################################################
## include custom variables
##

[ -f $SHELLOS_DIR/sbin/variables.custom ] && \
    source $SHELLOS_DIR/sbin/variables.custom
