#!/bin/bash

if [ -x $CMD_GIT ]; then

    cat << EOF > /.gitignore
/*

!$INSTALL_DIR
$INSTALL_DIR/*
EOF

    cat << EOF > $INSTALL_DIR/.gitignore
/*
!.gitignore
EOF
    [ -d $INSTALL_DIR/dovecot/etc ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/dovecot
/dovecot/*
!/dovecot/etc
EOF
    [ -d $INSTALL_DIR/geoip/etc ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/geoip
/geoip/*
!/geoip/etc
EOF
    [ -d $INSTALL_DIR/git/conf ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/git
/git/*
!/git/conf
EOF
    [ -d $INSTALL_DIR/host4ge/conf ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/host4ge
/host4ge/*
!/host4ge/conf
!/host4ge/etc
EOF
    [ -d $INSTALL_DIR/httpd/conf ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/httpd
/httpd/*
!/httpd/conf
EOF
    [ -d $INSTALL_DIR/lxc/conf ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/lxc
/lxc/*
!/lxc/conf
EOF
    [ -d $INSTALL_DIR/mysql/conf ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/mysql
/mysql/*
!/mysql/conf
EOF
    [ -d $INSTALL_DIR/nginx/conf ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/nginx
/nginx/*
!/nginx/conf
EOF
    [ -d $INSTALL_DIR/openssh/conf ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/openssh
/openssh/*
!/openssh/conf
EOF
    [ -d $INSTALL_DIR/openvpn/conf ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/openvpn
/openvpn/*
!/openvpn/conf
EOF
    [ -d $INSTALL_DIR/php/conf ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/php
/php/*
!/php/conf
EOF
    [ -d $INSTALL_DIR/php-fpm/conf ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/php-fpm
/php-fpm/*
!/php-fpm/conf
EOF
    [ -d $INSTALL_DIR/postfix/conf ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/postfix
/postfix/*
!/postfix/conf
EOF
    [ -d $INSTALL_DIR/proftpd/conf ] && cat <<EOF >> $INSTALL_DIR/.gitignore

!/proftpd
/proftpd/*
!/proftpd/conf
EOF

    chmod 400 /.gitignore
    chmod 400 $INSTALL_DIR/.gitignore
    cd /

    if [ "$SERVER_STATUS" == "installation" ]; then

        [ -d .git ] && rm -rf .git
        $CMD_GIT init && chmod 700 .git
        $CMD_GIT config user.name "$ADMIN_NAME"
        $CMD_GIT config user.email "$ADMIN_MAIL"
        $CMD_GIT config core.autocrlf false
        $CMD_GIT config core.filemode true
        $CMD_GIT add .
        $CMD_GIT commit -m "initial commit"
        repositories_add_dir /

    else

        if [ "$($git status -s | wc -l)" -gt 0 ]; then

            $CMD_GIT add .
            $CMD_GIT commit -m "update"

        fi

    fi

fi

exit 0
