#!/bin/bash

##
## welcome screen
##

# /etc/motd.tail
if [ -f /etc/motd.tail ] && [ ! -f /etc/motd.tail.old ]; then
    cp /etc/motd.tail /etc/motd.tail.old
fi
cat << EOF > /etc/motd.tail
    __               __  __ __
   / /_  ____  _____/ /_/ // / ____ ____   _________  ____ ___
  / __ \\/ __ \\/ ___/ __/ // /_/ __ \`/ _ \\ / ___/ __ \\/ __ \`__ \\
 / / / / /_/ (__  ) /_/__  __/ /_/ /  __// /__/ /_/ / / / / / /
/_/ /_/\\____/____/\\__/  /_/  \\__, /\\___(_)___/\\____/_/ /_/ /_/
                            /____/

EOF

exit 0
