#!/bin/bash

##
## check dependencies
##

if [ ! -f $INSTALL_DIR/imagemagick/bin/convert ]; then
    echo "Error: imagick module for PHP requires ImageMagick!"
    exit 1
fi

##
## functions
##

function install_imagick {

    local type=$1
    local php_imagick_install_dir=$2
    local php_imagick_ext_dir=$php_imagick_install_dir/lib/php/extensions/$(ls $php_imagick_install_dir/lib/php/extensions/)

    # download
    pkg_name="$type-imagick-$VER_PHP_MOD_IMAGICK"
    [ "$packages_force_compilation" == "N" ] && pkg_result=$(package_download $pkg_name)
    if [ "$pkg_result" != "success" ]; then
        url="http://pecl.php.net/get/imagick-$VER_PHP_MOD_IMAGICK.tgz"
        file=imagick-$VER_PHP_MOD_IMAGICK.tgz
        result=$(file_download --url $url --file $file --cache-dir-name downloads --check-file-size 50000)
        if [ "$result" == "error" ]; then
            echo "Error: Unable to download $file file!"
            exit 1
        fi
    fi

    # install
    if [ "$pkg_result" != "success" ]; then
        echo "Compile imagick module for PHP"
        [ -d imagick-$VER_PHP_MOD_IMAGICK ] && rm -rf imagick-$VER_PHP_MOD_IMAGICK
        tar -zxf imagick-$VER_PHP_MOD_IMAGICK.tgz
        cd imagick-$VER_PHP_MOD_IMAGICK
        export PKG_CONFIG_PATH=$INSTALL_DIR/imagemagick/lib/pkgconfig
        $php_imagick_install_dir/bin/phpize
        ./configure \
            --with-php-config=$php_imagick_install_dir/bin/php-config \
            --with-imagick=$INSTALL_DIR/imagemagick \
        && make && make install && echo "imagick module for PHP installed successfully in $php_imagick_install_dir!"
        cd ..
        echo "Strip symbols:"
        development_strip_symbols $php_imagick_ext_dir/imagick.so
        echo "Create package:"
        package_create_files $php_imagick_ext_dir $pkg_name imagick.so
    else
        echo "Install imagick module for PHP in $php_imagick_install_dir from package:"
        package_restore_files $pkg_name $php_imagick_ext_dir
    fi

    # check
    if [ ! -f $php_imagick_ext_dir/imagick.so ]; then
        echo "Error: imagick PHP extension has NOT been installed successfully in $php_imagick_install_dir"
        exit 1
    fi

    # configure
    if [ -f $php_imagick_install_dir/conf/php.ini ]; then
        replace_in_file "extension = imagick.so\n" "" $php_imagick_install_dir/conf/php.ini
        replace_in_file "; extensions end" "extension = imagick.so\n; extensions end" $php_imagick_install_dir/conf/php.ini
    fi

}

##
## main
##

install_imagick "php" $INSTALL_DIR/php
for php_imagick_dir_name in $INSTALL_DIR/php-fpm/*; do
    if [ -d $php_imagick_dir_name ]; then
        # SEE: php-fpm installation script
        php_fpm_ver="xx"
        if [[ $(basename $php_imagick_dir_name) == 5.3.* ]]; then
            php_fpm_ver=5.3
        fi
        if [[ $(basename $php_imagick_dir_name) == 5.4.* ]]; then
            php_fpm_ver=5.4
        fi
        if [[ $(basename $php_imagick_dir_name) == 5.5.* ]]; then
            php_fpm_ver=5.5
        fi
        if [ $php_fpm_ver != "xx" ]; then
            install_imagick "php-fpm-${php_fpm_ver}" $php_imagick_dir_name
        fi
    fi
done

##
## post install
##

[ -f package.xml ] && rm package.xml
rm php*imagick*${PACKAGE_SUFFIX} > /dev/null 2>&1
[ -f imagick-$VER_PHP_MOD_IMAGICK.tgz ] && rm imagick-$VER_PHP_MOD_IMAGICK.tgz
[ -d imagick-$VER_PHP_MOD_IMAGICK ] && rm -rf imagick-$VER_PHP_MOD_IMAGICK

# save package version
package_add_version "php-imagick" "$VER_PHP_MOD_IMAGICK"

exit 0

