#!/bin/bash

##
## welcome screen
##

# /etc/motd.tail
if [ -f /etc/motd.tail ] && [ ! -f /etc/motd.tail.old ]; then
    cp /etc/motd.tail /etc/motd.tail.old
fi
cat << EOF > /etc/motd.tail
               __       ____
          ___ / /  ___ / / /__  ___
         (_-</ _ \/ -_) / / _ \(_-<
        /___/_//_/\__/_/_/\___/___/


EOF

exit 0

