cd $LFS/sources

# binutils

tar -jxf binutils-2.18.tar.bz2
cd binutils-2.18
patch -Np1 -i ../binutils-2.18-configure-1.patch
mkdir -v ../binutils-build
cd ../binutils-build
time { CC="gcc -B/usr/bin/" ../binutils-2.18/configure --prefix=/tools --disable-nls --disable-werror &&  make && make install && make -C ld clean && make -C ld LIB_PATH=/tools/lib; }
cp -v ld/ld-new /tools/bin
cd ..
rm -rf binutils-2.18
rm -rf binutils-build

# gcc

tar -jxf gcc-4.3.2.tar.bz2
cd gcc-4.3.2
tar -jxf ../mpfr-2.3.2.tar.bz2
mv mpfr-2.3.2 mpfr
tar -jxf ../gmp-4.2.4.tar.bz2
mv gmp-4.2.4 gmp
mkdir -v ../gcc-build
cd ../gcc-build
CC="gcc -B/usr/bin/" ../gcc-4.3.2/configure --prefix=/tools --with-local-prefix=/tools --disable-nls --disable-shared --disable-libssp --enable-languages=c
make
make install
ln -vs libgcc.a `gcc -print-libgcc-file-name | sed 's/libgcc/&_eh/'`
ln -vs gcc /tools/bin/cc
cd ..
rm -rf gcc-4.3.2
rm -rf gcc-build

# linux api headers

tar -jxf  linux-2.6.27.4.tar.bz2
cd linux-2.6.27.4
make mrproper
make headers_check
make INSTALL_HDR_PATH=dest headers_install
cp -rv dest/include/* /tools/include
cd ..
rm -rf linux-2.6.27.4

# glib

tar -jxf  glibc-2.8-20080929.tar.bz2
cd glibc-2.8-20080929
sed -i 's@/etc/ld.so.preload@/tools/etc/ld.so.preload@' elf/rtld.c
mkdir -v ../glibc-build
cd ../glibc-build
echo "CFLAGS += -march=i486 -mtune=native" > configparms
../glibc-2.8-20080929/configure --prefix=/tools --disable-profile --enable-add-ons --enable-kernel=2.6.0 --with-binutils=/tools/bin --without-gd --with-headers=/tools/include --without-selinux
make
mkdir -v /tools/etc
touch /tools/etc/ld.so.conf
make install
cd ..
rm -rf glibc-2.8-20080929
rm -rf glibc-build

# adjusting the toolchain 

mv -v /tools/bin/{ld,ld-old}
mv -v /tools/$(gcc -dumpmachine)/bin/{ld,ld-old}
mv -v /tools/bin/{ld-new,ld}
ln -sv /tools/bin/ld /tools/$(gcc -dumpmachine)/bin/ld
gcc -dumpspecs | sed 's@/lib/ld-linux.so.2@/tools&@g' > `dirname $(gcc -print-libgcc-file-name)`/specs
GCC_FIXED=`dirname $(gcc -print-libgcc-file-name)`/include-fixed && find ${GCC_FIXED}/* -maxdepth 0 -xtype d -exec rm -rvf '{}' \; && rm -vf `grep -l "DO NOT EDIT THIS FILE" ${GCC_FIXED}/*` && unset GCC_FIXED

# tcl

tar -zxf  tcl8.5.5-src.tar.gz
cd tcl8.5.5
cd unix
./configure --prefix=/tools
make
#TZ=UTC make test
make install
chmod -v u+w /tools/lib/libtcl8.5.so
make install-private-headers
ln -sv tclsh8.5 /tools/bin/tclsh
cd ../..
rm -rf tcl8.5.5

# expect

tar -zxf expect-5.43.0.tar.gz
cd expect-5.43
patch -Np1 -i ../expect-5.43.0-spawn-1.patch
patch -Np1 -i ../expect-5.43.0-tcl_8.5.5_fix-1.patch
cp -v configure{,.orig}
sed 's:/usr/local/bin:/bin:' configure.orig > configure
./configure --prefix=/tools --with-tcl=/tools/lib --with-tclinclude=/tools/include --with-x=no
make
#make test
make SCRIPTS="" install
cd ..
rm -rf expect-5.43

# dejagnu

tar -zxf dejagnu-1.4.4.tar.gz
cd dejagnu-1.4.4
./configure --prefix=/tools
make install
cd ..
rm -rf dejagnu-1.4.4

# gcc pass 2

tar -jxf gcc-4.3.2.tar.bz2
cd gcc-4.3.2
#expect -c "spawn ls"
cp -v gcc/Makefile.in{,.orig}
sed 's@\./fixinc\.sh@-c true@' gcc/Makefile.in.orig > gcc/Makefile.in
cp -v gcc/Makefile.in{,.tmp}
sed 's/^XCFLAGS =$/& -fomit-frame-pointer/' gcc/Makefile.in.tmp > gcc/Makefile.in
for file in $(find gcc/config -name linux64.h -o -name linux.h)
do
  cp -uv $file{,.orig}
  sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' -e 's@/usr@/tools@g' $file.orig > $file
  echo "
#undef STANDARD_INCLUDE_DIR
#define STANDARD_INCLUDE_DIR 0" >> $file
  touch $file.orig
done
tar -jxf ../mpfr-2.3.2.tar.bz2
mv mpfr-2.3.2 mpfr
tar -jxf ../gmp-4.2.4.tar.bz2
mv gmp-4.2.4 gmp
mkdir -v ../gcc-build
cd ../gcc-build
../gcc-4.3.2/configure --prefix=/tools --with-local-prefix=/tools --enable-clocale=gnu --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-languages=c,c++ --disable-libstdcxx-pch --disable-bootstrap
make
#make -k check
make install
#echo 'main(){}' > dummy.c
#cc dummy.c
#readelf -l a.out | grep ': /tools'
#rm -v dummy.c a.out
cd ..
rm -rf gcc-4.3.2
rm -rf gcc-build

# binutils pass 2

tar -jxf binutils-2.18.tar.bz2
cd binutils-2.18
patch -Np1 -i ../binutils-2.18-configure-1.patch
mkdir -v ../binutils-build
cd ../binutils-build
../binutils-2.18/configure --prefix=/tools --disable-nls --with-lib-path=/tools/lib
make
#make check
make install
make -C ld clean
make -C ld LIB_PATH=/usr/lib:/lib
cp -v ld/ld-new /tools/bin
cd ..
rm -rf binutils-2.18
rm -rf binutils-build

# ncurses

tar -zxf ncurses-5.6.tar.gz
cd ncurses-5.6
./configure --prefix=/tools --with-shared --without-debug --without-ada --enable-overwrite
make
make install
cd ..
rm -rf ncurses-5.6

# bash

tar -zxf bash-3.2.tar.gz
cd bash-3.2
patch -Np1 -i ../bash-3.2-fixes-8.patch
./configure --prefix=/tools --without-bash-malloc ac_cv_func_working_mktime=yes
make
#make tests
make install
ln -vs bash /tools/bin/sh
cd ..
rm -rf bash-3.2

# bzip

tar -zxf bzip2-1.0.5.tar.gz
cd bzip2-1.0.5
make
make PREFIX=/tools install
cd ..
rm -rf bzip2-1.0.5

# coreutils

tar -zxf coreutils-6.12.tar.gz
cd coreutils-6.12
patch -Np1 -i ../coreutils-6.12-old_build_kernel-1.patch
./configure --prefix=/tools --enable-install-program=hostname
make
#make RUN_EXPENSIVE_TESTS=yes check
make install
cp -v src/su /tools/bin/su-tools
cd ..
rm -rf coreutils-6.12

# diffutils

tar -zxf diffutils-2.8.1.tar.gz
cd diffutils-2.8.1
./configure --prefix=/tools
make
make install
cd ..
rm -rf diffutils-2.8.1

# e2fsprogs

tar -zxf e2fsprogs-1.41.3.tar.gz
cd e2fsprogs-1.41.3
mkdir -v build
cd build
../configure --prefix=/tools
make
make install-libs
chmod -v u+w /tools/lib/{libblkid,libcom_err,libe2p,libext2fs,libss,libuuid}.a
cd ../..
rm -rf e2fsprogs-1.41.3

# findutils

tar -zxf findutils-4.4.0.tar.gz
cd findutils-4.4.0
./configure --prefix=/tools
make
#make check
make install
cd ..
rm -rf findutils-4.4.0

# gawk

tar -jxf gawk-3.1.6.tar.bz2
cd gawk-3.1.6
./configure --prefix=/tools ac_cv_func_working_mktime=yes
make
#make check
make install
cd ..
rm -rf gawk-3.1.6

# gettext

tar -zxf gettext-0.17.tar.gz
cd gettext-0.17
cd gettext-tools
./configure --prefix=/tools --disable-shared
make -C gnulib-lib
make -C src msgfmt
cp -v src/msgfmt /tools/bin
cd ../..
rm -rf gettext-0.17

# grep

tar -jxf grep-2.5.3.tar.bz2
cd grep-2.5.3
./configure --prefix=/tools --disable-perl-regexp --without-included-regex
make
#make check
make install
cd ..
rm -rf grep-2.5.3

# gzip

tar -zxf gzip-1.3.12.tar.gz
cd gzip-1.3.12
for file in gzip.c lib/utimens.{c,h} ; do cp -v $file{,.orig}
   sed 's/futimens/gl_&/' $file.orig > $file
done
./configure --prefix=/tools
make
#make check
make install
cd ..
rm -rf gzip-1.3.12

# m4

tar -jxf m4-1.4.12.tar.bz2
cd m4-1.4.12
./configure --prefix=/tools
make
#make check
make instal
cd ..
rm -rf m4-1.4.12

# make

tar -jxf make-3.81.tar.bz2
cd make-3.81
./configure --prefix=/tools
make
#make check
make instal
cd ..
rm -rf make-3.81

# patch

tar -zxf patch-2.5.4.tar.gz
cd patch-2.5.4
./configure --prefix=/tools
make
make instal
cd ..
rm -rf patch-2.5.4

# perl

tar -zxf perl-5.10.0.tar.gz
cd perl-5.10.0
patch -Np1 -i ../perl-5.10.0-consolidated-1.patch
sh Configure -des -Dprefix=/tools -Dstatic_ext='Data/Dumper Fcntl IO POSIX'
make perl utilities ext/Errno/pm_to_blib
cp -v perl pod/pod2man /tools/bin
mkdir -pv /tools/lib/perl5/5.10.0
cp -Rv lib/* /tools/lib/perl5/5.10.0
cd ..
rm -rf perl-5.10.0

# sed

tar -zxf sed-4.1.5.tar.gz
cd sed-4.1.5
./configure --prefix=/tools
make
#make check
make install
cd ..
rm -rf sed-4.1.5

# tar

tar -jxf tar-1.20.tar.bz2
cd tar-1.20
./configure --prefix=/tools
make
#make check
make install
cd ..
rm -rf tar-1.20

# textinfo

tar -zxf texinfo-4.13a.tar.gz
cd texinfo-4.13
./configure --prefix=/tools
make
#make check
make instal
cd ..
rm -rf texinfo-4.13

# util-linux-ng

tar -jxf util-linux-ng-2.14.1.tar.bz2
cd util-linux-ng-2.14.1
./configure --prefix=/tools
make BLKID_LIBS="-lblkid -luuid" -C mount mount umount
make -C text-utils more
cp -v mount/{,u}mount text-utils/more /tools/bin
cd ..
rm -rf util-linux-ng-2.14.1

# striping

strip --strip-debug /tools/lib/*
strip --strip-unneeded /tools/{,s}bin/*
rm -rf /tools/{info,man}
