#!/bin/bash
#
# Scheduled job. This script backups databases.

##
## includes
##

# variables
source $HOST4GE_DIR/conf/variables

# versions
source $HOST4GE_DIR/conf/versions

# include constants
source $HOST4GE_DIR/bin/constants

# include functions
source $HOST4GE_DIR/bin/functions

##
## main
##

t1=`date +%s`
msg=

# check lock
[ -f $JOB_LOCK_ALL_FILE ] && exit 0
if [ `job_lock_exists $( basename $0 )` == "yes" ]; then
    # do not log if all jobs are locked
    [ `job_lock_all_exists` == "no" ] && \
        logger -p local0.notice -t host4ge "job $( basename $0 ) is locked"
    exit 0
fi
# set lock
job_lock_set $( basename $0 )

# ---------- BEGIN ----------

# remove database backups older than three weeks
find $BACKUP_DATABASES_DIR/* -mtime +$JOB_BACKUP_DATABASES_REMOVE_DAYS -exec rm {} \;


db_pass=$(mysql_get_user_password root)

# dump databases
databases=$(echo "show databases;" | $CMD_MYSQL --user=root --password=$db_pass | awk '{ if ( NR > 1  ) { print } }')
timestamp=$(date +"%Y%m%d%H%M")
for db in $databases; do
    if [ ! "$db" == "mysql" ] && [ ! "$db" == "information_schema" ] && [ ! "$db" == "performance_schema" ]; then
        mysql_backup_database_to_archive $db $BACKUP_DATABASES_DIR/$db-$timestamp.tar.gz
    fi
done

# backup databases specific to the server role
[ -x $HOST4GE_DIR/job/$( basename $0 ).$ROLE_NAME ] && \
    (. $HOST4GE_DIR/job/$( basename $0 ).$ROLE_NAME)

# backup custom databases
[ -x $HOST4GE_DIR/job/$( basename $0 ).custom ] && \
    (. $HOST4GE_DIR/job/$( basename $0 ).custom)

db_pass=

# ---------- END ------------

# remove lock
job_lock_unset $( basename $0 )

# measure time
t2=`date +%s`
time=$((t2-t1))

# log an event only if it takes longer than specified number of seconds or there is a message
[ $time -le $JOB_LOG_EVENT_TIME ] && [ "$msg" == "" ] && exit 0
if [ "$msg" == "" ]; then
    logger -p local0.notice -t host4ge "job $( basename $0 ) run (time: $time s)"
else
    logger -p local0.notice -t host4ge "job $( basename $0 ) run - $msg (time: $time s)"
fi

exit 0
