#!/bin/bash
#
# USAGE: ./finalise --username "username"

##
## arguments
##

while [ "$1" != "" ]; do
    case $1 in
        --username) shift; username="$1"
                    ;;
    esac
    shift
done

##
## main
##

(

# file: sources.list
[ ! -f /etc/apt/sources.list.old ] && cp /etc/apt/sources.list /etc/apt/sources.list.old
cat << EOF > /etc/apt/sources.list
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://gb.archive.ubuntu.com/ubuntu/ precise main restricted
deb-src http://gb.archive.ubuntu.com/ubuntu/ precise main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://gb.archive.ubuntu.com/ubuntu/ precise-updates main restricted
deb-src http://gb.archive.ubuntu.com/ubuntu/ precise-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://gb.archive.ubuntu.com/ubuntu/ precise universe
deb-src http://gb.archive.ubuntu.com/ubuntu/ precise universe
deb http://gb.archive.ubuntu.com/ubuntu/ precise-updates universe
deb-src http://gb.archive.ubuntu.com/ubuntu/ precise-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://gb.archive.ubuntu.com/ubuntu/ precise multiverse
deb-src http://gb.archive.ubuntu.com/ubuntu/ precise multiverse
deb http://gb.archive.ubuntu.com/ubuntu/ precise-updates multiverse
deb-src http://gb.archive.ubuntu.com/ubuntu/ precise-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://gb.archive.ubuntu.com/ubuntu/ precise-backports main restricted universe multiverse
deb-src http://gb.archive.ubuntu.com/ubuntu/ precise-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu precise-security main restricted
deb-src http://security.ubuntu.com/ubuntu precise-security main restricted
deb http://security.ubuntu.com/ubuntu precise-security universe
deb-src http://security.ubuntu.com/ubuntu precise-security universe
deb http://security.ubuntu.com/ubuntu precise-security multiverse
deb-src http://security.ubuntu.com/ubuntu precise-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu precise partner
# deb-src http://archive.canonical.com/ubuntu precise partner

## This software is not part of Ubuntu, but is offered by third-party
## developers who want to ship their latest software.
deb http://extras.ubuntu.com/ubuntu precise main
deb-src http://extras.ubuntu.com/ubuntu precise main
EOF

apt_get_update="apt-get --yes update"
apt_get_upgrade="apt-get --yes --force-yes upgrade"
apt_get_remove="apt-get --yes --purge remove"
apt_get_install="apt-get --yes --force-yes --ignore-missing --no-install-recommends install"
apt_add_repository="apt-add-repository --yes"

DEBIAN_FRONTEND="noninteractive"

# update system packages
$apt_get_update
$apt_get_upgrade
apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade
apt-get autoremove --yes --force-yes
apt-get autoclean --yes --force-yes

# install desktop environment
$apt_get_install gnome-shell
cp -fv /home/$username/resources/wallpaper.jpg /home/$username

# install display driver
$apt_get_remove xserver-xorg-video-nouveau nvidia-173
$apt_add_repository ppa:ubuntu-x-swat/x-updates
$apt_get_update > /dev/null 2>&1
$apt_get_install nvidia-current nvidia-settings
cp -fv /home/$username/resources/xorg.conf /etc/X11/

# configure windows manager
cat << EOF > /etc/lightdm/lightdm.conf

[SeatDefaults]
allow-guest=false
greeter-session=unity-greeter
user-session=ubuntu-2d
EOF
cat << EOF > /home/$username/.dmrc

[Desktop]
Session=ubuntu-2d
EOF

# fix admin group name
groupadd -g 99 admin
usermod -a -G admin $username

) 2>&1 | tee /home/$username/finalise.log
chown root:root /home/$username/finalise.log
chmod 444 /home/$username/finalise.log
rm -f /home/$username/finalise
exit 0
