#!/bin/bash

##
## check dependencies
##

if [ ! -f $INSTALL_DIR/openjdk/bin/javac ]; then
    echo "Error: Tomcat requires OpenJDK!"
    exit 1
fi

##
## download
##

url="http://ftp.ps.pl/pub/apache//ant/binaries/apache-ant-$VER_ANT-bin.tar.gz"
file=apache-ant-$VER_ANT-bin.tar.gz
result=$(file_download --url $url --file $file --cache-dir-name downloads --check-file-size 5000000)
if [ "$result" == "error" ]; then
    echo "Error: Unable to download $file file!"
    exit 1
fi

##
## install
##

# extract
[ -d $INSTALL_DIR/ant ] && rm -rf $INSTALL_DIR/ant
tar -zxf $file
mv apache-ant-$VER_ANT $INSTALL_DIR/ant

# check
if [ ! -x $INSTALL_DIR/ant/bin/ant ]; then
    echo "Error: Ant has NOT been installed successfully!"
    exit 1
fi

##
## configure
##

# set files permission
chown -R root:root $INSTALL_DIR/ant

# remove file
[ -f $file ] && rm $file

# save package version
package_add_version "ant" "$VER_ANT"

# add directories to create hashes
hashes_add_dir $INSTALL_DIR/ant/bin
hashes_add_dir $INSTALL_DIR/ant/lib

exit 0

