#!/bin/bash

file=apache-ant-$VER_ANT-bin.tar.gz

# set files permission
chown -R root:root $INSTALL_DIR/ant

# remove file
[ -f $file ] && rm $file

# save package version
package_add_version "ant" "$VER_ANT"

# add directories to create hashes
hashes_add_dir $INSTALL_DIR/ant/bin
hashes_add_dir $INSTALL_DIR/ant/lib

exit 0
