#!/bin/bash

url="http://ftp.ps.pl/pub/apache//ant/binaries/apache-ant-$VER_ANT-bin.tar.gz"
file=apache-ant-$VER_ANT-bin.tar.gz

result=$(file_download --url $url --file $file --cache-dir-name downloads --check-file-size 5000000)
if [ "$result" == "error" ]; then
    echo "Error: Unable to download $file file!"
    exit 1
fi

exit 0
