#!/bin/bash

url="http://mirror.switch.ch/eclipse/technology/epp/downloads/release/juno/SR1/eclipse-$VER_ECLIPSE-linux-gtk-x86_64.tar.gz"
file=eclipse-$VER_ECLIPSE-linux-gtk-x86_64.tar.gz

result=$(file_download --url $url --file $file --cache-dir-name downloads --check-file-size 200000000)
if [ "$result" == "error" ]; then
    echo "Error: Unable to download $file file!"
    exit 1
fi

exit 0
